name: Daily Commit Workflow

on:
  schedule:
    - cron: '27 4 * * *'  # Runs every day at 04:27 UTC (adjust as needed)
  workflow_dispatch:  # allows manual runs for testing

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add dummy file - 21f2001474@ds.study.iitm.ac.in
        run: |
          echo "Updated on $(date)" >> daily-log.txt
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "21f2001474@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Daily update"
          git push
